apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service-monitor
  namespace: monitoring       
  labels:
    release: monitoring-stack 
spec:
  selector:
    matchLabels:
      app: auth-service       # Connects to the app
  namespaceSelector:
    matchNames:
      - securebankingops      # The Namespace where the app lives
  endpoints:
  - port: http-metrics       
    path: /metrics
    interval: 15s