apiVersion: v1
kind: Service
metadata:
  name: {{ include "accounts.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5001
  selector:
    app: {{ include "accounts.name" . }}
