apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: frontend.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service-auth-service
                port:
                  number: 5000
          - path: /accounts
            pathType: Prefix
            backend:
              service:
                name: accounts-accounts
                port:
                  number: 5001
          - path: /payments
            pathType: Prefix
            backend:
              service:
                name: payments-payments
                port:
                  number: 5002
