apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Abdulmuid1/SecureBankingOps_Project'
    path: 'helm-charts/auth-service'
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: securebankingops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
