apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-availability
  namespace: observability
spec:
  selector:
    matchLabels:
      app: auth-service
  endpoints:
  - port: http
    path: /health
